---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    driver:
      box: chef/ubuntu-12.04
    run_list:
      - recipe[apt::default]

  - name: centos-6.5
    driver:
      box: chef/centos-6.5
    run_list:
      - recipe[yum::default]

suites:
  - name: default
    run_list:
      - recipe[cve-2014-7169::default]
    attributes:

